Add nan test and docs
bigladder/btwxt pull request #32
Opened 2023-07-05 15:39 UTC by spahrenk

Added null_implementation_test.
Transcribed pp presentation.

2023-07-10 13:35 UTC, tanaya-mankad commented on docs/discussion.md
> +To find $f(x)$ for $x$ in $(x_0,x_0)$,
Did you mean (x_0, x_1)?

2023-07-10 13:40 UTC, tanaya-mankad commented on docs/figs/fig_1Dcubic.png
These figures are super. We also need to check in the source code used to generate them.

2023-07-10 13:46 UTC, tanaya-mankad commented on docs/discussion.md
> +## 2-D Linear pseudocode
I think markdown supports a "code block" formatting, which we could use for pseudocode. - indenting the lines, maybe.

2023-07-10 13:54 UTC, tanaya-mankad commented on docs/discussion.md
> +Group the coefficients:
:)

2023-07-10 13:55 UTC, tanaya-mankad commented on docs/discussion.md
> +There are 4<sup>N</sup> points to weigh. Number of calculations grows faster than that.
A few sentences seem to have gotten fragmented; these just need to read more fluidly.

2023-07-12 01:34 UTC, tanaya-mankad commented on docs/figs/btwxt presentation.pptx
I think I made a mistake in viewing the figures - I thought the png files were from your own code that had generated  plots of the different cubic splines. If so, then you'd check in that code (Python or whatever). The pptx file is binary and I don't think it makes sense to commit it to the repository. @nealkruis what's your opinion?

2023-07-12 02:08 UTC, tanaya-mankad requested changes

2023-07-12 02:08 UTC, tanaya-mankad commented on docs/discussion.md
> +for each vertex x[i][j] in the hypercube:
This pseudocode is maybe useful, but it's not descriptive enough. What does `dim` range over? `vertex_weight` could use an earlier mention. `i` and `j` don't imply N dimensions to me, which is I think what we're after here (the slides used `...k` as well, but then didn't carry it through the loop).

2023-07-12 02:08 UTC, tanaya-mankad commented on docs/discussion.md
> +## 2-D Linear pseudocode
Actually I think the 2-D linear pseudocode is both distracting and anyway you'd unroll the loop if you wrote it as real code, not think of it in this conditional format. Maybe we remove this?

2023-07-12 02:08 UTC, tanaya-mankad commented on docs/discussion.md
> +## 1-D Linear
Should there be a hyphen between the "1" and "D"? It looks funny but I guess we'd want it for "N-D"...

2023-07-18 16:20 UTC, tanaya-mankad commented on docs/discussion.md
> +1) the known funciton values are closely spaced, such that variations between neighboring points are within acceptable tolerances, or
typo: funciton

2023-07-18 16:22 UTC, tanaya-mankad commented on docs/discussion.md
> +Terms $c_{0}$ and $c_{1}$ are referred to as *interpolation coefficients*.
interpolation_coefficients (with the underscore, as below)

2023-07-18 16:52 UTC, tanaya-mankad requested changes
Really minor change requests this time. I really like how this flows; I can understand our assumptions and the algebra has just the right amount of explicitness for my personal taste!

2023-07-19 15:26 UTC, spahrenk reviewed
done

2023-07-20 01:49 UTC, tanaya-mankad approved these changes

2023-07-20 16:16 UTC, nealkruis requested changes
This is very close! Thanks, @spahrenk!

Mostly minor details here.

Do we want to include source code changes here too?

2023-07-20 16:16 UTC, nealkruis commented on docs/discussion.md
> +The above formulation allows cubic interpolation using the four function values associated with the grid-point coordinates in the vicinity of the queried coordinate. Notice that our slope estimations
I wonder if we should break the discussion about edges into a new subheading?

2023-07-20 16:16 UTC, nealkruis commented on docs/discussion.md
> +**btwxt** also enables *extrapolation* for estimation of the function outside the valid interpolation range. Two methods for extrapolation are available: *constant* and *linear*. If constant is selec
Separate heading for extrapolation? This isn't specific to cubic interpolation. Maybe this should be moved after we're done discussing cubic interpolation?

2023-07-20 16:16 UTC, nealkruis commented on docs/discussion.md
> +As for the 2-D linear case, the coefficient for each vertex is the product of the coefficients computed for each axis, separately. Therefore, we first find the $2\cdot4=8$ single-axis coefficients, t
Should this say "As for the 2-D cubic case..."? What coefficients are we referring to here? I think we're talking about weighting factors (per the following paragraph)?

2023-07-20 16:16 UTC, nealkruis commented on docs/discussion.md
> +There are four coefficients along each axis, and 4N total. Each vertex is weighted by the product among all axes of the weighting factors for each axis.
Missing superscript?

2023-07-20 16:16 UTC, nealkruis commented on docs/discussion.md
> +## *Big Ladder Software*
Maybe replace these lines with a single title that better describes the content of this document? The file name is "discussion.md", but I feel that isn't the most descriptive name. What if we call the file "methodology.md", and make the title "btwxt Methodology"?

2023-07-24 20:58 UTC, nealkruis commented on docs/discussion.md
> +We define:
The corresponding addition doesn't appear to be rendering correctly.

2023-07-24 21:03 UTC, nealkruis commented on docs/discussion.md
> +As for the 2-D linear case, the coefficient for each vertex is the product of the coefficients computed for each axis, separately. Therefore, we first find the $2\cdot4=8$ single-axis coefficients, t
This doesn't seem to be clarified in the changes. I suspect "coefficient" is really talking about the "weighting factor".

2023-07-24 21:04 UTC, nealkruis commented on docs/discussion.md
> +There are four coefficients along each axis, and 4N total. Each vertex is weighted by the product among all axes of the weighting factors for each axis.
Still shows `4N`, when the "N" should be superscript.

2023-07-31 18:41 UTC, nealkruis commented on docs/methodology.md
> +</p>
This still doesn't look like it's matching the approximated slopes from the previous figure.

2023-07-31 18:54 UTC, tanaya-mankad commented on docs/methodology.md
> +The coefficient multiplying each function value comprises the *weight* of the *vertex* located at the corresponding 2-D grid-point coordinates. The weight for that vertex is simply the product of the
👍

2023-07-31 18:56 UTC, tanaya-mankad commented on docs/figs/fig_2D_linear.png
I kinda liked the first image, but probably the new one is more descriptive. :)

2023-07-31 18:56 UTC, tanaya-mankad approved these changes

2023-08-02 20:00 UTC, tanaya-mankad reviewed
I don't have any context for what this commit was intended to accomplish, so I can't give a relevant review. In the future, you could add an explanatory comment of your own to the "conversation" section of the PR, and/or be a little more descriptive in the commit message (Also, please use the internal message style starting with a capital letter: “{Present-tense action} {on the thing this commit fixes}. “

2023-08-02 20:27 UTC, spahrenk commented
Curve colors had been reversed in the most recent commit. An attempt was made to correct this.

2023-08-08 15:28 UTC, spahrenk commented
Replaced actual slopes with estimated slope son cubic figure.

2023-08-08 15:36 UTC, nealkruis approved these changes

2023-08-08 15:36 UTC, merged